title: ""
labels: ["Wallpaper"]
body:
  - type: input
    id: resolution
    attributes:
      label: Wallpaper Resolution
      description: Dimension of the Wallpaper (IE: 1920x1080)
    validations:
      required: true
  - type: dropdown
    id: genre
    attributes:
      label: Wallpaper Genre
      options:
        - Abstract
        - Animal
        - Anime
        - Cartoon
        - CGI
        - Cyberpunk
        - Fantasy
        - Game
        - Girls
        - Guys
        - Landscape
        - Medieval
        - Memes
        - Music
        - Nature
        - Pixel art
        - Relaxing
        - Retro
        - Sci-Fi
        - Sports
        - Technology
        - Television
        - Vehicle
        - Unspecified genre
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      value: |
        ...
      render: bash
    validations:
      required: false
